### ISSUE TITLE
Possiblity of backport to 3.x?

### ISSUE THREAD

**Issue by ill13** [SpyrexDE/SmoothScroll#20]
For newbies like me, Godot 4 has many changes and very little documentation so far, regardless, this plugin is awesome, 

Any chance you would consider back porting your Godot 4 version to Godot 3.x?

**Comment by SpyrexDE** [comment]
Yeah, this will be some work but as soon as the current Godot 4 version of the plugin is cleaned up/refactored and released I will try my best to update the Godot 3 version with the new systems for e.g. touch support as well. 👍

**Comment by urokai95** [comment]
I made a quick downgrade for the script. I had no time to bugtest everything but it works. I couldnt upload the .gd file and pasting killed the formatting due to markup so I attached it as .txt. I didn't add it to the addon, just to a script for a ScrollContainer since I only needed it there,
[ScrollContainer.txt](https://github.com/SpyrexDE/SmoothScroll/files/13774962/ScrollContainer.txt)

**Comment by SpyrexDE** [comment]
@urokai95 Thank you so much for the effort! I added you as a contributor to the release notes of the Godot 3 backport. It will be up in the asset library soon.
