### ISSUE TITLE
Scrollcontainer overdrags too far on fast mouse movement

### ISSUE THREAD

**Issue by SpyrexDE** [SpyrexDE/SmoothScroll#27]
![overdragBack](https://github.com/SpyrexDE/SmoothScroll/assets/57133330/f2610a99-b2e0-4b7a-9c84-3d9fe13ab516)
The issue only exists when the mouse is moved fast enough.

**Comment by HaroldLever** [comment]
I might have found where the problem is.

For example, assuming damping=0.1, at frame 1 you drag down 50 pixel, the formular calculate with "distance=0", resulting 50, however at frame 2 you drag up -50 pixel, the formular calculate with "distance=50" from last frame, resulting -8.33, way more less to drag back.

I'm afraid handle_content_dragging() function should be refactored totally, sadly I haven't come up with any idea yet. Do you have any good idea?

**Comment by SpyrexDE** [comment]
I think the issue is I described here is just a symptom of a bigger one: If the mouse is moved too fast while dragging the traveled distance of the smooth scroll is way higher than when the mouse is moved slowly.
