### ISSUE TITLE
Can't seem to set vertical scroll

### ISSUE THREAD

**Issue by nzrinyi** [SpyrexDE/SmoothScroll#48]
Employing the following code doesn't seem to work for me. Seems pretty elementary, is there perhaps a setting to enable the use of script to adjust scroll position?
`$SmoothScrollContainer.scroll_vertical = 0`

The code is not in the ready function, and just in case I've also tried to defer to no avail.

**Comment by SpyrexDE** [comment]
For setting the scroll position, please use the `SmoothScrollContainer.scroll_y_to(y_pos: float, duration:float=0.5)` and `SmoothScrollContainer.scroll_x_to(x_pos: float, duration:float=0.5)`. If you don't want the smoothing you can just set the duration parameter to `0`.

Generally try to use the custom functions offered by the script instead of the basic ones offered by `ScrollContainer` if possible. Otherwise, many features won't work due to the `SmoothScrollScript` overwriting many properties. To see all custom functions of the script, go to the script tab and click on "Search Help". Then enter "SmoothScrollContainer" and press enter. Now you should see the documentation page of the SmoothScrollContainer class.
